#!/bin/bash

usage() {
  echo "$(basename $0) <request> <value> <index> [data]"
  exit 1
}

cd $(dirname "$0")
source init_env

check_tool usbtool

usb_req=$1
if [ ! $usb_req ]; then
  error "Request is not specified"
fi

usb_val=$2
if [ ! $usb_val ]; then
  error "Value is not specified"
fi

usb_index=$3
if [ ! $usb_index ]; then
  error "Index is not specified"
fi

data="$4"
if [ "$data" ]; then
  # Convert data to the format expected by usbtool, e.g. "abc" -> "0x61,0x62,0x63"
  data=$(printf "$data" | xxd -p -c 1 | paste -sd , | sed 's/\([^,]*\)/0x\1/g')
  data_arg="-d $data"
fi

# Send "out" request
usbtool -v 0x$USB_VENDOR_ID -p 0x$USB_PRODUCT_ID $data_arg control out vendor device $usb_req $usb_val $usb_index > /dev/null
